platform :ios, '13.0'
use_frameworks!

target '__APP_NAME__' do
  # Lynx SDK
  pod 'Lynx', '~> 3.4.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
